# Generated by Django 2.1.7 on 2019-05-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='sponser_logos')),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
