# Generated by Django 2.1.7 on 2019-05-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
