# Generated by Django 2.1.7 on 2019-05-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_pictures_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pics',
            field=models.ImageField(upload_to='past_pics'),
        ),
    ]
