# Generated by Django 2.1.7 on 2019-03-04 16:21

from django.db import migrations
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190304_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
        ),
    ]
