# Generated by Django 2.1.7 on 2019-03-04 21:11

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190304_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=embed_video.fields.EmbedVideoField(default='Enter a URL'),
        ),
    ]
